apiVersion: vault.in-cloud.io/v1alpha1
kind: VaultConfig
metadata:
  name: vault-secret
  labels:
    vault.in-cloud.io/owner: vault-secret
spec:
  address: https://vault.beget.com:8200
  managerAuth:
    method: kubernetes
    mountPath: kubernetes-mgmt
    role: vault-secret-operator
  storage:
    kvMountPath: secret
