apiVersion: vault.in-cloud.io/v1alpha1
kind: VaultSecretClaim
metadata:
  name: ec8a00
  namespace: dlputi1u
spec:
  vaultConfigRef:
    name: vault-secret
  clusterRef:
    name: ec8a00
  secretsPrefix: clusters/ec8a00
  deletionPolicy: Retain
  secretList:
    - name: argocd-admin
      type: generate
      destination:
        path: argocd
        key: admin.password
        hashedKey: admin.passwordBcrypt
      generate:
        length: 16
        hash: bcrypt
    - name: vmagent
      type: generate
      destination:
        path: monitoring/vmagent
        key: password
      generate:
        length: 24
        hash: none
    - name: grafana-oidc
      type: copy
      source:
        path: system/dex
        key: staticClient
      destination:
        path: grafana
        key: staticClient
    - name: etcd-backup-s3
      type: copy
      source:
        path: system/etcd
        key: s3Creds
      destination:
        path: etcd-backup
        key: s3Creds
