apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: bucket-operator
    app.kubernetes.io/name: bucket-operator
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: bucket-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: bucket-operator
    app.kubernetes.io/name: bucket-operator
spec:
  selector:
    matchLabels:
      control-plane: bucket-operator
      app.kubernetes.io/name: bucket-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: bucket-operator
        app.kubernetes.io/name: bucket-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /bucket-operator
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --cloud-manager-addr=grpc-internal.svc-cloud-manager.service.consul:50051
          - --default-s3-configuration-id=s3_v1
        image: controller:latest
        name: manager
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
