// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: cloud.proto

// Minimal subset of the cloud-manager cloud contract: only create with the s3
// arm. Field numbers, proto package and RPC name must match the server.

package cloudmanagerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CustomerIdentifier string                 `protobuf:"bytes,1,opt,name=customer_identifier,json=customerIdentifier,proto3" json:"customer_identifier,omitempty"`
	ConfigurationId    string                 `protobuf:"bytes,2,opt,name=configuration_id,json=configurationId,proto3" json:"configuration_id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Params:
	//
	//	*CreateRequest_S3Params
	Params        isCreateRequest_Params `protobuf_oneof:"params"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_cloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetCustomerIdentifier() string {
	if x != nil {
		return x.CustomerIdentifier
	}
	return ""
}

func (x *CreateRequest) GetConfigurationId() string {
	if x != nil {
		return x.ConfigurationId
	}
	return ""
}

func (x *CreateRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetParams() isCreateRequest_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CreateRequest) GetS3Params() *CreateParams {
	if x != nil {
		if x, ok := x.Params.(*CreateRequest_S3Params); ok {
			return x.S3Params
		}
	}
	return nil
}

func (x *CreateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type isCreateRequest_Params interface {
	isCreateRequest_Params()
}

type CreateRequest_S3Params struct {
	S3Params *CreateParams `protobuf:"bytes,6,opt,name=s3_params,json=s3Params,proto3,oneof"`
}

func (*CreateRequest_S3Params) isCreateRequest_Params() {}

type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in cloud.proto.
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateResponse_ServiceInfo
	//	*CreateResponse_S3Error
	Result        isCreateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_cloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_cloud_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in cloud.proto.
func (x *CreateResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *CreateResponse) GetResult() isCreateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateResponse) GetServiceInfo() *Service {
	if x != nil {
		if x, ok := x.Result.(*CreateResponse_ServiceInfo); ok {
			return x.ServiceInfo
		}
	}
	return nil
}

func (x *CreateResponse) GetS3Error() *CreateError {
	if x != nil {
		if x, ok := x.Result.(*CreateResponse_S3Error); ok {
			return x.S3Error
		}
	}
	return nil
}

type isCreateResponse_Result interface {
	isCreateResponse_Result()
}

type CreateResponse_ServiceInfo struct {
	ServiceInfo *Service `protobuf:"bytes,2,opt,name=service_info,json=serviceInfo,proto3,oneof"`
}

type CreateResponse_S3Error struct {
	S3Error *CreateError `protobuf:"bytes,3,opt,name=s3_error,json=s3Error,proto3,oneof"`
}

func (*CreateResponse_ServiceInfo) isCreateResponse_Result() {}

func (*CreateResponse_S3Error) isCreateResponse_Result() {}

// Credentials are read via CloudS3Service.findAll, so only id is modelled.
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_cloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_cloud_proto protoreflect.FileDescriptor

const file_cloud_proto_rawDesc = "" +
	"\n" +
	"\vcloud.proto\x12'beget.internal.cloud.cloudManager.cloud\x1a\bs3.proto\"\xa8\x02\n" +
	"\rCreateRequest\x12/\n" +
	"\x13customer_identifier\x18\x01 \x01(\tR\x12customerIdentifier\x12)\n" +
	"\x10configuration_id\x18\x02 \x01(\tR\x0fconfigurationId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12T\n" +
	"\ts3_params\x18\x06 \x01(\v25.beget.internal.cloud.cloudManager.s3.s3.CreateParamsH\x00R\bs3Params\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06regionB\b\n" +
	"\x06params\"\x94\x02\n" +
	"\x0eCreateResponse\x12N\n" +
	"\aservice\x18\x01 \x01(\v20.beget.internal.cloud.cloudManager.cloud.ServiceB\x02\x18\x01R\aservice\x12U\n" +
	"\fservice_info\x18\x02 \x01(\v20.beget.internal.cloud.cloudManager.cloud.ServiceH\x00R\vserviceInfo\x12Q\n" +
	"\bs3_error\x18\x03 \x01(\v24.beget.internal.cloud.cloudManager.s3.s3.CreateErrorH\x00R\as3ErrorB\b\n" +
	"\x06result\"\x19\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8b\x01\n" +
	"\fCloudService\x12{\n" +
	"\x06create\x126.beget.internal.cloud.cloudManager.cloud.CreateRequest\x1a7.beget.internal.cloud.cloudManager.cloud.CreateResponse\"\x00BSZQgithub.com/PRO-Robotech/vault-operator/internal/cloudmanager/proto;cloudmanagerpbb\x06proto3"

var (
	file_cloud_proto_rawDescOnce sync.Once
	file_cloud_proto_rawDescData []byte
)

func file_cloud_proto_rawDescGZIP() []byte {
	file_cloud_proto_rawDescOnce.Do(func() {
		file_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_proto_rawDesc), len(file_cloud_proto_rawDesc)))
	})
	return file_cloud_proto_rawDescData
}

var file_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: beget.internal.cloud.cloudManager.cloud.CreateRequest
	(*CreateResponse)(nil), // 1: beget.internal.cloud.cloudManager.cloud.CreateResponse
	(*Service)(nil),        // 2: beget.internal.cloud.cloudManager.cloud.Service
	(*CreateParams)(nil),   // 3: beget.internal.cloud.cloudManager.s3.s3.CreateParams
	(*CreateError)(nil),    // 4: beget.internal.cloud.cloudManager.s3.s3.CreateError
}
var file_cloud_proto_depIdxs = []int32{
	3, // 0: beget.internal.cloud.cloudManager.cloud.CreateRequest.s3_params:type_name -> beget.internal.cloud.cloudManager.s3.s3.CreateParams
	2, // 1: beget.internal.cloud.cloudManager.cloud.CreateResponse.service:type_name -> beget.internal.cloud.cloudManager.cloud.Service
	2, // 2: beget.internal.cloud.cloudManager.cloud.CreateResponse.service_info:type_name -> beget.internal.cloud.cloudManager.cloud.Service
	4, // 3: beget.internal.cloud.cloudManager.cloud.CreateResponse.s3_error:type_name -> beget.internal.cloud.cloudManager.s3.s3.CreateError
	0, // 4: beget.internal.cloud.cloudManager.cloud.CloudService.create:input_type -> beget.internal.cloud.cloudManager.cloud.CreateRequest
	1, // 5: beget.internal.cloud.cloudManager.cloud.CloudService.create:output_type -> beget.internal.cloud.cloudManager.cloud.CreateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cloud_proto_init() }
func file_cloud_proto_init() {
	if File_cloud_proto != nil {
		return
	}
	file_s3_proto_init()
	file_cloud_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateRequest_S3Params)(nil),
	}
	file_cloud_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateResponse_ServiceInfo)(nil),
		(*CreateResponse_S3Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_proto_rawDesc), len(file_cloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_proto_goTypes,
		DependencyIndexes: file_cloud_proto_depIdxs,
		MessageInfos:      file_cloud_proto_msgTypes,
	}.Build()
	File_cloud_proto = out.File
	file_cloud_proto_goTypes = nil
	file_cloud_proto_depIdxs = nil
}
