// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: s3.proto

// Minimal subset of the cloud-manager S3 contract. Field numbers, proto package
// and RPC names must match the server wire format.

package cloudmanagerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_RUNNING  Status = 0
	Status_CREATING Status = 1
	Status_REMOVING Status = 2
	Status_REMOVED  Status = 3
	Status_ERROR    Status = 4
	Status_STOPPED  Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "RUNNING",
		1: "CREATING",
		2: "REMOVING",
		3: "REMOVED",
		4: "ERROR",
		5: "STOPPED",
	}
	Status_value = map[string]int32{
		"RUNNING":  0,
		"CREATING": 1,
		"REMOVING": 2,
		"REMOVED":  3,
		"ERROR":    4,
		"STOPPED":  5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_s3_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_s3_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{0}
}

type S3BucketManagedBy int32

const (
	S3BucketManagedBy_SYSTEM   S3BucketManagedBy = 0
	S3BucketManagedBy_CUSTOMER S3BucketManagedBy = 1
)

// Enum value maps for S3BucketManagedBy.
var (
	S3BucketManagedBy_name = map[int32]string{
		0: "SYSTEM",
		1: "CUSTOMER",
	}
	S3BucketManagedBy_value = map[string]int32{
		"SYSTEM":   0,
		"CUSTOMER": 1,
	}
)

func (x S3BucketManagedBy) Enum() *S3BucketManagedBy {
	p := new(S3BucketManagedBy)
	*p = x
	return p
}

func (x S3BucketManagedBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S3BucketManagedBy) Descriptor() protoreflect.EnumDescriptor {
	return file_s3_proto_enumTypes[1].Descriptor()
}

func (S3BucketManagedBy) Type() protoreflect.EnumType {
	return &file_s3_proto_enumTypes[1]
}

func (x S3BucketManagedBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S3BucketManagedBy.Descriptor instead.
func (S3BucketManagedBy) EnumDescriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{1}
}

type CreateError_Code int32

const (
	CreateError_CODE_RESERVED              CreateError_Code = 0
	CreateError_INSUFFICIENT_FUNDS         CreateError_Code = 1
	CreateError_CONFIGURATION_NOT_FOUND    CreateError_Code = 2
	CreateError_INVALID_DISPLAY_NAME       CreateError_Code = 4
	CreateError_BUCKET_NAME_ALREADY_EXISTS CreateError_Code = 8
	CreateError_INVALID_BUCKET_NAME        CreateError_Code = 9
	CreateError_BUCKET_LIMIT_REACHED       CreateError_Code = 10
	CreateError_INVALID_DESCRIPTION        CreateError_Code = 11
)

// Enum value maps for CreateError_Code.
var (
	CreateError_Code_name = map[int32]string{
		0:  "CODE_RESERVED",
		1:  "INSUFFICIENT_FUNDS",
		2:  "CONFIGURATION_NOT_FOUND",
		4:  "INVALID_DISPLAY_NAME",
		8:  "BUCKET_NAME_ALREADY_EXISTS",
		9:  "INVALID_BUCKET_NAME",
		10: "BUCKET_LIMIT_REACHED",
		11: "INVALID_DESCRIPTION",
	}
	CreateError_Code_value = map[string]int32{
		"CODE_RESERVED":              0,
		"INSUFFICIENT_FUNDS":         1,
		"CONFIGURATION_NOT_FOUND":    2,
		"INVALID_DISPLAY_NAME":       4,
		"BUCKET_NAME_ALREADY_EXISTS": 8,
		"INVALID_BUCKET_NAME":        9,
		"BUCKET_LIMIT_REACHED":       10,
		"INVALID_DESCRIPTION":        11,
	}
)

func (x CreateError_Code) Enum() *CreateError_Code {
	p := new(CreateError_Code)
	*p = x
	return p
}

func (x CreateError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_s3_proto_enumTypes[2].Descriptor()
}

func (CreateError_Code) Type() protoreflect.EnumType {
	return &file_s3_proto_enumTypes[2]
}

func (x CreateError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateError_Code.Descriptor instead.
func (CreateError_Code) EnumDescriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{2, 0}
}

type Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        bool                   `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustLogin     string                 `protobuf:"bytes,3,opt,name=cust_login,json=custLogin,proto3" json:"cust_login,omitempty"`
	AccessKey     string                 `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Fqdn          string                 `protobuf:"bytes,6,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=beget.internal.cloud.cloudManager.s3.s3.Status" json:"status,omitempty"`
	Cname         string                 `protobuf:"bytes,11,opt,name=cname,proto3" json:"cname,omitempty"`
	ManagedBy     S3BucketManagedBy      `protobuf:"varint,15,opt,name=managed_by,json=managedBy,proto3,enum=beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedBy" json:"managed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_s3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{0}
}

func (x *Bucket) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bucket) GetCustLogin() string {
	if x != nil {
		return x.CustLogin
	}
	return ""
}

func (x *Bucket) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Bucket) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Bucket) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *Bucket) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RUNNING
}

func (x *Bucket) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

func (x *Bucket) GetManagedBy() S3BucketManagedBy {
	if x != nil {
		return x.ManagedBy
	}
	return S3BucketManagedBy_SYSTEM
}

type CreateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        bool                   `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	BucketName    string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Fqdn          string                 `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	ManagedBy     S3BucketManagedBy      `protobuf:"varint,4,opt,name=managed_by,json=managedBy,proto3,enum=beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedBy" json:"managed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParams) Reset() {
	*x = CreateParams{}
	mi := &file_s3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParams) ProtoMessage() {}

func (x *CreateParams) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParams.ProtoReflect.Descriptor instead.
func (*CreateParams) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{1}
}

func (x *CreateParams) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *CreateParams) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateParams) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *CreateParams) GetManagedBy() S3BucketManagedBy {
	if x != nil {
		return x.ManagedBy
	}
	return S3BucketManagedBy_SYSTEM
}

type CreateError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          CreateError_Code       `protobuf:"varint,2,opt,name=code,proto3,enum=beget.internal.cloud.cloudManager.s3.s3.CreateError_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateError) Reset() {
	*x = CreateError{}
	mi := &file_s3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateError) ProtoMessage() {}

func (x *CreateError) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateError.ProtoReflect.Descriptor instead.
func (*CreateError) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{2}
}

func (x *CreateError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateError) GetCode() CreateError_Code {
	if x != nil {
		return x.Code
	}
	return CreateError_CODE_RESERVED
}

type FindAllRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Scope         []*FindAllRequest_SearchScope `protobuf:"bytes,1,rep,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest) Reset() {
	*x = FindAllRequest{}
	mi := &file_s3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest) ProtoMessage() {}

func (x *FindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest.ProtoReflect.Descriptor instead.
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllRequest) GetScope() []*FindAllRequest_SearchScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        []*Bucket              `protobuf:"bytes,1,rep,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_s3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllResponse) GetBucket() []*Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

type RemoveBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBucketRequest) Reset() {
	*x = RemoveBucketRequest{}
	mi := &file_s3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBucketRequest) ProtoMessage() {}

func (x *RemoveBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBucketRequest.ProtoReflect.Descriptor instead.
func (*RemoveBucketRequest) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type RemoveBucketResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Error         *RemoveBucketResponse_Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBucketResponse) Reset() {
	*x = RemoveBucketResponse{}
	mi := &file_s3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBucketResponse) ProtoMessage() {}

func (x *RemoveBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBucketResponse.ProtoReflect.Descriptor instead.
func (*RemoveBucketResponse) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveBucketResponse) GetError() *RemoveBucketResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FindAllRequest_SearchScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*FindAllRequest_SearchScope_ByCustomer
	//	*FindAllRequest_SearchScope_ByBucket
	Condition     isFindAllRequest_SearchScope_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest_SearchScope) Reset() {
	*x = FindAllRequest_SearchScope{}
	mi := &file_s3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest_SearchScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest_SearchScope) ProtoMessage() {}

func (x *FindAllRequest_SearchScope) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest_SearchScope.ProtoReflect.Descriptor instead.
func (*FindAllRequest_SearchScope) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FindAllRequest_SearchScope) GetCondition() isFindAllRequest_SearchScope_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *FindAllRequest_SearchScope) GetByCustomer() *FindAllRequest_SearchScope_ByCustomerLogin {
	if x != nil {
		if x, ok := x.Condition.(*FindAllRequest_SearchScope_ByCustomer); ok {
			return x.ByCustomer
		}
	}
	return nil
}

func (x *FindAllRequest_SearchScope) GetByBucket() *FindAllRequest_SearchScope_ByBucketName {
	if x != nil {
		if x, ok := x.Condition.(*FindAllRequest_SearchScope_ByBucket); ok {
			return x.ByBucket
		}
	}
	return nil
}

type isFindAllRequest_SearchScope_Condition interface {
	isFindAllRequest_SearchScope_Condition()
}

type FindAllRequest_SearchScope_ByCustomer struct {
	ByCustomer *FindAllRequest_SearchScope_ByCustomerLogin `protobuf:"bytes,1,opt,name=by_customer,json=byCustomer,proto3,oneof"`
}

type FindAllRequest_SearchScope_ByBucket struct {
	ByBucket *FindAllRequest_SearchScope_ByBucketName `protobuf:"bytes,2,opt,name=by_bucket,json=byBucket,proto3,oneof"`
}

func (*FindAllRequest_SearchScope_ByCustomer) isFindAllRequest_SearchScope_Condition() {}

func (*FindAllRequest_SearchScope_ByBucket) isFindAllRequest_SearchScope_Condition() {}

type FindAllRequest_SearchScope_ByCustomerLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         []string               `protobuf:"bytes,1,rep,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest_SearchScope_ByCustomerLogin) Reset() {
	*x = FindAllRequest_SearchScope_ByCustomerLogin{}
	mi := &file_s3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest_SearchScope_ByCustomerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest_SearchScope_ByCustomerLogin) ProtoMessage() {}

func (x *FindAllRequest_SearchScope_ByCustomerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest_SearchScope_ByCustomerLogin.ProtoReflect.Descriptor instead.
func (*FindAllRequest_SearchScope_ByCustomerLogin) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *FindAllRequest_SearchScope_ByCustomerLogin) GetLogin() []string {
	if x != nil {
		return x.Login
	}
	return nil
}

type FindAllRequest_SearchScope_ByBucketName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []string               `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest_SearchScope_ByBucketName) Reset() {
	*x = FindAllRequest_SearchScope_ByBucketName{}
	mi := &file_s3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest_SearchScope_ByBucketName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest_SearchScope_ByBucketName) ProtoMessage() {}

func (x *FindAllRequest_SearchScope_ByBucketName) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest_SearchScope_ByBucketName.ProtoReflect.Descriptor instead.
func (*FindAllRequest_SearchScope_ByBucketName) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *FindAllRequest_SearchScope_ByBucketName) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type RemoveBucketResponse_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBucketResponse_Error) Reset() {
	*x = RemoveBucketResponse_Error{}
	mi := &file_s3_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBucketResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBucketResponse_Error) ProtoMessage() {}

func (x *RemoveBucketResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_s3_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBucketResponse_Error.ProtoReflect.Descriptor instead.
func (*RemoveBucketResponse_Error) Descriptor() ([]byte, []int) {
	return file_s3_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RemoveBucketResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_s3_proto protoreflect.FileDescriptor

const file_s3_proto_rawDesc = "" +
	"\n" +
	"\bs3.proto\x12'beget.internal.cloud.cloudManager.s3.s3\"\xdf\x02\n" +
	"\x06Bucket\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cust_login\x18\x03 \x01(\tR\tcustLogin\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\x12\x12\n" +
	"\x04fqdn\x18\x06 \x01(\tR\x04fqdn\x12G\n" +
	"\x06status\x18\a \x01(\x0e2/.beget.internal.cloud.cloudManager.s3.s3.StatusR\x06status\x12\x14\n" +
	"\x05cname\x18\v \x01(\tR\x05cname\x12Y\n" +
	"\n" +
	"managed_by\x18\x0f \x01(\x0e2:.beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedByR\tmanagedBy\"\xb6\x01\n" +
	"\fCreateParams\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\x12\n" +
	"\x04fqdn\x18\x03 \x01(\tR\x04fqdn\x12Y\n" +
	"\n" +
	"managed_by\x18\x04 \x01(\x0e2:.beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedByR\tmanagedBy\"\xcd\x02\n" +
	"\vCreateError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12M\n" +
	"\x04code\x18\x02 \x01(\x0e29.beget.internal.cloud.cloudManager.s3.s3.CreateError.CodeR\x04code\"\xd4\x01\n" +
	"\x04Code\x12\x11\n" +
	"\rCODE_RESERVED\x10\x00\x12\x16\n" +
	"\x12INSUFFICIENT_FUNDS\x10\x01\x12\x1b\n" +
	"\x17CONFIGURATION_NOT_FOUND\x10\x02\x12\x18\n" +
	"\x14INVALID_DISPLAY_NAME\x10\x04\x12\x1e\n" +
	"\x1aBUCKET_NAME_ALREADY_EXISTS\x10\b\x12\x17\n" +
	"\x13INVALID_BUCKET_NAME\x10\t\x12\x18\n" +
	"\x14BUCKET_LIMIT_REACHED\x10\n" +
	"\x12\x17\n" +
	"\x13INVALID_DESCRIPTION\x10\v\"\xbe\x03\n" +
	"\x0eFindAllRequest\x12Y\n" +
	"\x05scope\x18\x01 \x03(\v2C.beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScopeR\x05scope\x1a\xd0\x02\n" +
	"\vSearchScope\x12v\n" +
	"\vby_customer\x18\x01 \x01(\v2S.beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByCustomerLoginH\x00R\n" +
	"byCustomer\x12o\n" +
	"\tby_bucket\x18\x02 \x01(\v2P.beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByBucketNameH\x00R\bbyBucket\x1a'\n" +
	"\x0fByCustomerLogin\x12\x14\n" +
	"\x05login\x18\x01 \x03(\tR\x05login\x1a\"\n" +
	"\fByBucketName\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04nameB\v\n" +
	"\tcondition\"Z\n" +
	"\x0fFindAllResponse\x12G\n" +
	"\x06bucket\x18\x01 \x03(\v2/.beget.internal.cloud.cloudManager.s3.s3.BucketR\x06bucket\"6\n" +
	"\x13RemoveBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"\x94\x01\n" +
	"\x14RemoveBucketResponse\x12Y\n" +
	"\x05error\x18\x01 \x01(\v2C.beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse.ErrorR\x05error\x1a!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*V\n" +
	"\x06Status\x12\v\n" +
	"\aRUNNING\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\f\n" +
	"\bREMOVING\x10\x02\x12\v\n" +
	"\aREMOVED\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\v\n" +
	"\aSTOPPED\x10\x05*-\n" +
	"\x11S3BucketManagedBy\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x00\x12\f\n" +
	"\bCUSTOMER\x10\x012\xa0\x02\n" +
	"\x0eCloudS3Service\x12~\n" +
	"\afindAll\x127.beget.internal.cloud.cloudManager.s3.s3.FindAllRequest\x1a8.beget.internal.cloud.cloudManager.s3.s3.FindAllResponse\"\x00\x12\x8d\x01\n" +
	"\fremoveBucket\x12<.beget.internal.cloud.cloudManager.s3.s3.RemoveBucketRequest\x1a=.beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse\"\x00BSZQgithub.com/PRO-Robotech/vault-operator/internal/cloudmanager/proto;cloudmanagerpbb\x06proto3"

var (
	file_s3_proto_rawDescOnce sync.Once
	file_s3_proto_rawDescData []byte
)

func file_s3_proto_rawDescGZIP() []byte {
	file_s3_proto_rawDescOnce.Do(func() {
		file_s3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s3_proto_rawDesc), len(file_s3_proto_rawDesc)))
	})
	return file_s3_proto_rawDescData
}

var file_s3_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_s3_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_s3_proto_goTypes = []any{
	(Status)(0),                                        // 0: beget.internal.cloud.cloudManager.s3.s3.Status
	(S3BucketManagedBy)(0),                             // 1: beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedBy
	(CreateError_Code)(0),                              // 2: beget.internal.cloud.cloudManager.s3.s3.CreateError.Code
	(*Bucket)(nil),                                     // 3: beget.internal.cloud.cloudManager.s3.s3.Bucket
	(*CreateParams)(nil),                               // 4: beget.internal.cloud.cloudManager.s3.s3.CreateParams
	(*CreateError)(nil),                                // 5: beget.internal.cloud.cloudManager.s3.s3.CreateError
	(*FindAllRequest)(nil),                             // 6: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest
	(*FindAllResponse)(nil),                            // 7: beget.internal.cloud.cloudManager.s3.s3.FindAllResponse
	(*RemoveBucketRequest)(nil),                        // 8: beget.internal.cloud.cloudManager.s3.s3.RemoveBucketRequest
	(*RemoveBucketResponse)(nil),                       // 9: beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse
	(*FindAllRequest_SearchScope)(nil),                 // 10: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope
	(*FindAllRequest_SearchScope_ByCustomerLogin)(nil), // 11: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByCustomerLogin
	(*FindAllRequest_SearchScope_ByBucketName)(nil),    // 12: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByBucketName
	(*RemoveBucketResponse_Error)(nil),                 // 13: beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse.Error
}
var file_s3_proto_depIdxs = []int32{
	0,  // 0: beget.internal.cloud.cloudManager.s3.s3.Bucket.status:type_name -> beget.internal.cloud.cloudManager.s3.s3.Status
	1,  // 1: beget.internal.cloud.cloudManager.s3.s3.Bucket.managed_by:type_name -> beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedBy
	1,  // 2: beget.internal.cloud.cloudManager.s3.s3.CreateParams.managed_by:type_name -> beget.internal.cloud.cloudManager.s3.s3.S3BucketManagedBy
	2,  // 3: beget.internal.cloud.cloudManager.s3.s3.CreateError.code:type_name -> beget.internal.cloud.cloudManager.s3.s3.CreateError.Code
	10, // 4: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.scope:type_name -> beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope
	3,  // 5: beget.internal.cloud.cloudManager.s3.s3.FindAllResponse.bucket:type_name -> beget.internal.cloud.cloudManager.s3.s3.Bucket
	13, // 6: beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse.error:type_name -> beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse.Error
	11, // 7: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.by_customer:type_name -> beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByCustomerLogin
	12, // 8: beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.by_bucket:type_name -> beget.internal.cloud.cloudManager.s3.s3.FindAllRequest.SearchScope.ByBucketName
	6,  // 9: beget.internal.cloud.cloudManager.s3.s3.CloudS3Service.findAll:input_type -> beget.internal.cloud.cloudManager.s3.s3.FindAllRequest
	8,  // 10: beget.internal.cloud.cloudManager.s3.s3.CloudS3Service.removeBucket:input_type -> beget.internal.cloud.cloudManager.s3.s3.RemoveBucketRequest
	7,  // 11: beget.internal.cloud.cloudManager.s3.s3.CloudS3Service.findAll:output_type -> beget.internal.cloud.cloudManager.s3.s3.FindAllResponse
	9,  // 12: beget.internal.cloud.cloudManager.s3.s3.CloudS3Service.removeBucket:output_type -> beget.internal.cloud.cloudManager.s3.s3.RemoveBucketResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_s3_proto_init() }
func file_s3_proto_init() {
	if File_s3_proto != nil {
		return
	}
	file_s3_proto_msgTypes[7].OneofWrappers = []any{
		(*FindAllRequest_SearchScope_ByCustomer)(nil),
		(*FindAllRequest_SearchScope_ByBucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s3_proto_rawDesc), len(file_s3_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s3_proto_goTypes,
		DependencyIndexes: file_s3_proto_depIdxs,
		EnumInfos:         file_s3_proto_enumTypes,
		MessageInfos:      file_s3_proto_msgTypes,
	}.Build()
	File_s3_proto = out.File
	file_s3_proto_goTypes = nil
	file_s3_proto_depIdxs = nil
}
