// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: s3.proto

// Minimal subset of the cloud-manager S3 contract. Field numbers, proto package
// and RPC names must match the server wire format.

package cloudmanagerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudS3Service_FindAll_FullMethodName      = "/beget.internal.cloud.cloudManager.s3.s3.CloudS3Service/findAll"
	CloudS3Service_RemoveBucket_FullMethodName = "/beget.internal.cloud.cloudManager.s3.s3.CloudS3Service/removeBucket"
)

// CloudS3ServiceClient is the client API for CloudS3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bucket creation lives in cloud.CloudService.create with s3_params.
type CloudS3ServiceClient interface {
	FindAll(ctx context.Context, in *FindAllRequest, opts ...grpc.CallOption) (*FindAllResponse, error)
	RemoveBucket(ctx context.Context, in *RemoveBucketRequest, opts ...grpc.CallOption) (*RemoveBucketResponse, error)
}

type cloudS3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudS3ServiceClient(cc grpc.ClientConnInterface) CloudS3ServiceClient {
	return &cloudS3ServiceClient{cc}
}

func (c *cloudS3ServiceClient) FindAll(ctx context.Context, in *FindAllRequest, opts ...grpc.CallOption) (*FindAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllResponse)
	err := c.cc.Invoke(ctx, CloudS3Service_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudS3ServiceClient) RemoveBucket(ctx context.Context, in *RemoveBucketRequest, opts ...grpc.CallOption) (*RemoveBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBucketResponse)
	err := c.cc.Invoke(ctx, CloudS3Service_RemoveBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudS3ServiceServer is the server API for CloudS3Service service.
// All implementations must embed UnimplementedCloudS3ServiceServer
// for forward compatibility.
//
// Bucket creation lives in cloud.CloudService.create with s3_params.
type CloudS3ServiceServer interface {
	FindAll(context.Context, *FindAllRequest) (*FindAllResponse, error)
	RemoveBucket(context.Context, *RemoveBucketRequest) (*RemoveBucketResponse, error)
	mustEmbedUnimplementedCloudS3ServiceServer()
}

// UnimplementedCloudS3ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudS3ServiceServer struct{}

func (UnimplementedCloudS3ServiceServer) FindAll(context.Context, *FindAllRequest) (*FindAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedCloudS3ServiceServer) RemoveBucket(context.Context, *RemoveBucketRequest) (*RemoveBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBucket not implemented")
}
func (UnimplementedCloudS3ServiceServer) mustEmbedUnimplementedCloudS3ServiceServer() {}
func (UnimplementedCloudS3ServiceServer) testEmbeddedByValue()                        {}

// UnsafeCloudS3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudS3ServiceServer will
// result in compilation errors.
type UnsafeCloudS3ServiceServer interface {
	mustEmbedUnimplementedCloudS3ServiceServer()
}

func RegisterCloudS3ServiceServer(s grpc.ServiceRegistrar, srv CloudS3ServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudS3ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudS3Service_ServiceDesc, srv)
}

func _CloudS3Service_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudS3ServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudS3Service_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudS3ServiceServer).FindAll(ctx, req.(*FindAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudS3Service_RemoveBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudS3ServiceServer).RemoveBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudS3Service_RemoveBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudS3ServiceServer).RemoveBucket(ctx, req.(*RemoveBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudS3Service_ServiceDesc is the grpc.ServiceDesc for CloudS3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudS3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beget.internal.cloud.cloudManager.s3.s3.CloudS3Service",
	HandlerType: (*CloudS3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "findAll",
			Handler:    _CloudS3Service_FindAll_Handler,
		},
		{
			MethodName: "removeBucket",
			Handler:    _CloudS3Service_RemoveBucket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s3.proto",
}
